### ISSUE TITLE
Add ArPaymentCreate but not the legacy version

### ISSUE THREAD

**Issue by gabisanmartin12** [Intacct/intacct-sdk-js#45]
I need to create an AR Payment using the new create function on the ARPYMT object. You implemented the legacy version that creates an ARPAYMENT object instead. I need to know:

- Is it on your road map implement this version of this function?
- Is there any way to do what I need?
- Must I adjust to the legacy version? 

Thanks in advance!

**Comment by kmanske81** [comment]
Currently we don't support ARPYMT object as part of the SDK.

The legacy version supports some functionality such as Advances that are currently not supported in the ARPYMT object. Our approach is to only expose one flavor of an API object. Therefore we decided to keep the legacy object to further support advances.

We have checked with the owner of AR API objects and they confirmed that AR Advances will be refactored in the first half of 2022.

In the meantime, you could create an additional object in your local copy in order to support both flavors. If you like you can also issue a pull request with your changes if you decide to support ARPYMT.

Please let us know if you have any other questions.
